# Level data: the scene, the people watching you and what they say.
# Line fields:
#   who   index of the person speaking (-1 = you, reading your speech cards)
#   t     text
#   cue   expected expression: 0 serious, 1 smile, 2 sad
#   ev    events fired when the line starts ("shake:2", "sweat:3", "itch:1",
#         "thought:2", "sneeze", "feedback", "lookall")
#   hint  post-it shown to teach a mechanic
#   reply your (nervous) answer
#   react crowd reaction (wedding)
extends RefCounted

static var LEVELS := [
	{
		"name": "A Entrevista",
		"style": 0,
		"outfit": 0,
		"diff": 1.0,
		"song": "l0",
		"goal": "Sobreviva à entrevista sem desmoronar.",
		"photo": "foto do crachá",
		"verdicts": [[75, "CONTRATADO!"], [45, "ENTRAREMOS EM CONTATO"], [0, "VAGA PREENCHIDA"]],
		"fail": "ENTREVISTA ENCERRADA",
		"people": [
			{"name": "Dra. Brandão", "pos": Vector2(965, 578), "scale": 1.0,
				"skin": Color(0.86, 0.64, 0.5), "hair": Color(0.2, 0.14, 0.12), "hstyle": "bun",
				"cloth": Color(0.24, 0.32, 0.52), "acc": ["glasses", "badge"], "prop": "clipboard",
				"voice": 1.25, "weight": 1.0, "away": Vector2(2.6, 5.0), "look": Vector2(1.6, 3.0)},
		],
		"lines": [
			{"who": 0, "t": "Bom dia! Pode sentar. Relaxa, é só uma conversinha.", "cue": 0,
				"hint": "Quando o OLHO no topo abrir, ela está te observando. Mantenha o rosto inteiro!",
				"reply": "Bom dia! Tudo ótimo por aqui."},
			{"who": 0, "t": "Me fala um pouco sobre você.", "cue": 0, "ev": ["shake:2"],
				"hint": "Seu rosto está se desfazendo! ARRASTE as peças de volta pro lugar.",
				"reply": "Então... eu sou uma pessoa... que existe."},
			{"who": 0, "t": "Hm. E por que você quer trabalhar aqui?", "cue": 0, "ev": ["shake:1"],
				"reply": "Eu amo... planilhas. De verdade."},
			{"who": 0, "t": "Haha! Todo mundo diz isso.", "cue": 1,
				"hint": "Ela riu. SORRIA junto! Teclas 1 2 3 (ou roda do mouse) mudam sua expressão.",
				"reply": "Hehe. Pois é."},
			{"who": 0, "t": "Qual é o seu maior defeito?", "cue": 0, "ev": ["shake:2", "sweat:4"],
				"hint": "Suor! Clique (ou arraste segurando) sobre as gotas antes que pinguem.",
				"reply": "Sou perfeccionista... e sincero demais. E pontual."},
			{"who": 0, "t": "Uau. Que original.", "cue": 0, "ev": ["shake:1"],
				"reply": "..."},
			{"who": 0, "t": "Aqui somos uma família! Uma família que faz hora extra.", "cue": 1, "ev": ["shake:2"],
				"reply": "Adoro família! E hora... extra."},
			{"who": 0, "t": "Você trabalha bem sob pressão?", "cue": 0, "ev": ["shake:3", "sweat:3"],
				"hint": "Segure ESPAÇO para respirar fundo e se acalmar. Mas bochecha inflada é estranho: não deixe ela ver!",
				"reply": "Pressão? Que pressão? Hahaha."},
			{"who": 0, "t": "O último que sentou aí... não aguentou. Coitado.", "cue": 2, "ev": ["itch:2"],
				"hint": "Peças tremendo vão cair! SEGURE-as com o mouse, ou BOTÃO DIREITO para colar com fita.",
				"reply": "Nossa. Sinto muito."},
			{"who": 0, "t": "Onde você se vê daqui a cinco anos?", "cue": 0, "ev": ["shake:3", "sweat:2"],
				"reply": "Aqui! Ou numa praia. Aqui na praia."},
			{"who": 0, "t": "E a sua pretensão salarial?", "cue": 0, "ev": ["shake:2", "itch:1", "sweat:3"],
				"reply": "O que vocês acharem justo... mais uns trocados."},
			{"who": 0, "t": "Ótimo! Muito obrigada. Entraremos em contato.", "cue": 1, "ev": ["shake:2", "lookall"],
				"reply": "Eu que agradeço!"},
		],
	},
	{
		"name": "Jantar com os Sogros",
		"style": 1,
		"outfit": 1,
		"diff": 1.2,
		"song": "l1",
		"goal": "Conquiste a família. Os dois estão de olho.",
		"photo": "foto de família",
		"verdicts": [[75, "A FAMÍLIA APROVOU"], [45, "VOLTE NO NATAL"], [0, "VAMOS VER..."]],
		"fail": "JANTAR ENCERRADO",
		"people": [
			{"name": "Dona Célia", "pos": Vector2(850, 580), "scale": 0.92,
				"skin": Color(0.93, 0.74, 0.62), "hair": Color(0.62, 0.56, 0.7), "hstyle": "curly",
				"cloth": Color(0.62, 0.2, 0.3), "acc": ["pearls"], "prop": "glass",
				"voice": 1.4, "weight": 1.0, "away": Vector2(3.0, 6.0), "look": Vector2(1.5, 2.8)},
			{"name": "Seu Otávio", "pos": Vector2(1130, 580), "scale": 0.98,
				"skin": Color(0.8, 0.58, 0.44), "hair": Color(0.35, 0.3, 0.28), "hstyle": "bald",
				"cloth": Color(0.3, 0.45, 0.32), "acc": ["mustache", "glasses"], "prop": "fork",
				"voice": 0.75, "weight": 1.0, "away": Vector2(3.5, 7.0), "look": Vector2(1.8, 3.2)},
		],
		"lines": [
			{"who": 0, "t": "Que bom que você veio! Senta, senta, fiz lasanha!", "cue": 1,
				"hint": "Dois pares de olhos agora. Cuidado com os dois!",
				"reply": "Que cheiro maravilhoso!"},
			{"who": 1, "t": "Então você é o famoso... como é mesmo o seu nome?", "cue": 0, "ev": ["shake:2"],
				"reply": "É... é o de sempre."},
			{"who": 0, "t": "A gente ouve falar MUITO de você.", "cue": 1, "ev": ["sweat:3"],
				"reply": "Coisas boas, espero. Hehe. Né?"},
			{"who": 1, "t": "E você trabalha com o quê, exatamente?", "cue": 0, "ev": ["shake:2", "thought:2"],
				"hint": "Pensamentos intrusivos! Clique neles antes que cubram seu rosto.",
				"reply": "Com... coisas. Digitais. Na nuvem."},
			{"who": 0, "t": "Prova a lasanha. Receita da minha mãe, que Deus a tenha.", "cue": 2, "ev": ["itch:1"],
				"reply": "Hmm! Dá pra sentir o amor. E o luto."},
			{"who": 1, "t": "Eu fui contra esse namoro desde o começo, sabe.", "cue": 0, "ev": ["shake:3", "sweat:3"],
				"reply": "Ah é? Hahaha. Haha. Ha."},
			{"who": 0, "t": "Otávio! Passa a pimenta pra visita.", "cue": 0, "ev": ["sneeze"],
				"hint": "Atchim! Um espirro sacode o rosto inteiro.",
				"reply": "Obrig... ATCHIM!"},
			{"who": 1, "t": "Brincadeira! Haha. ...Mais ou menos.", "cue": 1, "ev": ["itch:2", "thought:1"],
				"reply": "Haha! Adoro piadas."},
			{"who": 0, "t": "E os netos, vêm quando?", "cue": 0, "ev": ["shake:3", "sweat:4", "thought:2"],
				"reply": "Netos? Nós? Tipo... bebês?"},
			{"who": 1, "t": "Pra que time você torce?", "cue": 0, "ev": ["shake:2", "itch:1"],
				"reply": "Pro... seu? Pro seu!"},
			{"who": 0, "t": "O Biscoito gostou de você. Ele não gosta de ninguém.", "cue": 1, "ev": ["thought:2", "sneeze"],
				"reply": "Adoro cachorros! Ai. Ele mordeu."},
			{"who": 1, "t": "Tá bom. Bem-vindo à família.", "cue": 1, "ev": ["shake:3", "lookall"],
				"reply": "Valeu! De verdade! Obrigado!"},
		],
	},
	{
		"name": "O Discurso",
		"style": 2,
		"outfit": 2,
		"diff": 1.35,
		"song": "l2",
		"goal": "Faça o discurso do casamento. Todo mundo está olhando.",
		"photo": "foto do casamento",
		"verdicts": [[75, "DISCURSO LENDÁRIO"], [45, "APLAUSOS EDUCADOS"], [0, "NINGUÉM VAI ESQUECER"]],
		"fail": "MICROFONE CORTADO",
		"people": [],
		"lines": [
			{"who": -1, "t": "Boa noite, gente! Nossa, quanta gente. Tanta gente olhando.", "cue": 1, "ev": ["shake:1"],
				"hint": "Agora é TODO MUNDO. Cada convidado olhando conta um pouco.", "react": "(silêncio)"},
			{"who": -1, "t": "Conheço o noivo desde o prézinho. Ele comia massinha.", "cue": 1, "ev": ["shake:2"],
				"react": "(risadas)"},
			{"who": -1, "t": "E a noiva... a noiva é... alguém que eu conheci hoje.", "cue": 0, "ev": ["sweat:4", "shake:2"],
				"react": "(tosse)"},
			{"who": -1, "t": "Mas o amor deles é lindo. Como um... como um... hm.", "cue": 2, "ev": ["thought:3", "itch:1"],
				"react": "(awnn)"},
			{"who": -1, "t": "*o microfone apita*", "cue": 0, "ev": ["feedback"],
				"hint": "Microfonia! Se remonte depressa."},
			{"who": -1, "t": "Queria agradecer o bufê. Os camarões estavam... vivos.", "cue": 1, "ev": ["shake:3", "sweat:3"],
				"react": "(risadas nervosas)"},
			{"who": -1, "t": "Vó, sei que a senhora queria estar aqui. Ah, você está aqui. Oi, vó.", "cue": 2, "ev": ["shake:3", "itch:2"],
				"react": "(oi!)"},
			{"who": -1, "t": "Um brinde ao... ao... qual é o nome dele mesmo?", "cue": 0, "ev": ["thought:3", "sweat:3", "sneeze"],
				"react": "TIO: FALA MAIS ALTO!"},
			{"who": -1, "t": "Brincadeira! Ao Rafa e à Bia!", "cue": 1, "ev": ["shake:3", "itch:1"],
				"react": "(aplausos)"},
			{"who": -1, "t": "Que sejam felizes. E que o bufê seja investigado. SAÚDE!", "cue": 1, "ev": ["shake:4", "itch:2", "sweat:3", "lookall"],
				"react": "SAÚDE!"},
		],
	},
]
